[platformio]
default_envs = mega-controller, esp32-gateway
src_dir = src
lib_dir = lib
test_dir = test

[env]
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra

[env:mega-controller]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter =
    +<mega-controller/>
    -<esp32-gateway/>
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3

[env:esp32-gateway]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
build_src_filter =
    +<esp32-gateway/>
    -<mega-controller/>
lib_deps =
    homespan/HomeSpan @ ^1.9.1

[env:native]
platform = native
test_framework = unity
test_build_src = no
build_src_filter = -<*>
build_flags =
    -std=gnu++11
    -Wall
    -Wextra
