[platformio]
default_envs = mega-controller
src_dir = src
lib_dir = lib
test_dir = test

[env]
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra

[env:mega-controller]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter =
    +<mega-controller/>
lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3

[env:native]
platform = native
test_framework = unity
test_build_src = no
build_src_filter = -<*>
build_flags =
    -std=gnu++11
    -Wall
    -Wextra
